# Generated by Django 5.1.7 on 2025-03-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_skill_proficiency'),
    ]

    operations = [
    ]
